[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[cro-chain-desktop]
source = "github"
github = "crypto-com/chain-desktop-wallet"
use_latest_release = true
prefix = "v"

[cro-chain-desktop-bin]
source = "github"
github = "crypto-com/chain-desktop-wallet"
use_latest_release = true
prefix = "v"

[cro-chain-maind-bin]
source = "github"
github = "crypto-org-chain/chain-main"
use_latest_release = true
prefix = "v"

[kaizen]
source = "regex"
url = "https://www.elastic-kaizen.com/download.html"
regex = "6\\.[0-9]+\\.[0-9]+"

[koofr]
source = "httpheader"
regex = "koofr-([a-z0-9]*)-linux"
url = "https://app.koofr.net/dl/apps/linux64"
header = "content-disposition"

[ledger-live]
source = "regex"
url = "https://raw.githubusercontent.com/LedgerHQ/ledger-live/main/apps/ledger-live-desktop/RELEASE_NOTES.md"
regex = "# ([0-9]+\\.[0-9]+\\.[0-9]+)"

[ledger-live-bin]
source = "httpheader"
url = "https://download.live.ledger.com/latest/linux"
regex = "([0-9]+\\.[0-9]+\\.[0-9]+)"
header = "location"

[oxen-core]
source = "github"
github = "oxen-io/oxen-core"
use_latest_release = true
prefix = "v"

[oxen-electron-wallet]
source = "github"
github = "oxen-io/oxen-electron-gui-wallet"
use_latest_release = true
prefix = "v"

[oxen-electron-wallet-bin]
source = "github"
github = "oxen-io/oxen-electron-gui-wallet"
use_latest_release = true
prefix = "v"

[prey-node-client]
source = "github"
github = "prey/prey-node-client"
use_latest_release = true
prefix = "v"

[proto]
source = "github"
github = "moonrepo/proto"
use_latest_release = true
prefix = "v"

[proto-bin]
source = "github"
github = "moonrepo/proto"
use_latest_release = true
prefix = "v"

[solidity]
source = "github"
github = "ethereum/solidity"
use_latest_release = true
prefix = "v"

[solidity-bin]
source = "github"
github = "ethereum/solidity"
use_latest_release = true
prefix = "v"

[xawtv]
source = "git"
git = "https://git.linuxtv.org/xawtv3.git"
prefix = "xawtv-"
