[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[ledger-live]
source = "github"
github = "LedgerHQ/ledger-live-desktop"
use_latest_release = true
prefix = "v"

[ledger-live-bin]
source = "github"
github = "LedgerHQ/ledger-live-desktop"
use_latest_release = true
prefix = "v"

[cro-chain-maind-bin]
source = "github"
github = "crypto-org-chain/chain-main"
use_latest_release = true
prefix = "v"

[cro-chain-desktop]
source = "github"
github = "crypto-com/chain-desktop-wallet"
use_latest_release = true
prefix = "v"

[cro-chain-desktop-bin]
source = "github"
github = "crypto-com/chain-desktop-wallet"
use_latest_release = true
prefix = "v"

[prey-node-client]
source = "github"
github = "prey/prey-node-client"
use_latest_release = true
prefix = "v"

[kaizen]
source = "regex"
url = "https://www.elastic-kaizen.com/download.html"
regex = "5\\.[0-9]+\\.[0-9]+"

[dolphin-megasync-bin]
source = "regex"
url = "https://mega.nz/linux/MEGAsync/Arch_Extra/x86_64/"
regex = "dolphin-megasync-([0-9].[0-9].[0-9]-[0-9])"

[koofr]
source = "httpheader"
regex = "koofr-([a-z0-9]*)-linux"
url = "https://app.koofr.net/dl/apps/linux64"
header = "content-disposition"
