[__config__]
oldver = "ver.json"
newver = "nver.json"

[cro-chain-desktop]
source = "github"
github = "crypto-com/chain-desktop-wallet"
use_latest_release = true
prefix = "v"

[cro-chain-maind]
source = "github"
github = "crypto-org-chain/chain-main"
use_latest_release = true
prefix = "v"

[kaizen]
source = "regex"
url = "https://www.elastic-kaizen.com/download.html"
regex = "6\\.[0-9]+\\.[0-9]+"

[ledger-live]
source = "httpheader"
url = "https://download.live.ledger.com/latest/linux"
regex = "([0-9]+\\.[0-9]+\\.[0-9]+)"
header = "location"

[oxen-core]
source = "github"
github = "oxen-io/oxen-core"
use_latest_release = true
prefix = "v"

[oxen-electron-wallet]
source = "github"
github = "oxen-io/oxen-electron-gui-wallet"
use_latest_release = true
prefix = "v"

[prey-node-client]
source = "github"
github = "prey/prey-node-client"
use_latest_release = true
prefix = "v"

[proto]
source = "github"
github = "moonrepo/proto"
use_latest_release = true
prefix = "v"

[solidity]
source = "github"
github = "ethereum/solidity"
use_latest_release = true
prefix = "v"

[xawtv]
source = "git"
git = "https://git.linuxtv.org/xawtv3.git"
prefix = "xawtv-"
