[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[ledger-live]
source = "github"
github = "LedgerHQ/ledger-live"
use_max_tag = true
include_regex = "@ledgerhq/live-desktop@([0-9]+\\.[0-9]+\\.[0-9]+)"
prefix = "@ledgerhq/live-desktop@"
